services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nexus
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrate:
    build:
      context: ./backend/migrations
      dockerfile: Dockerfile
    depends_on:
      - postgres

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/nexus?sslmode=disable
      - OLLAMA_URL=http://ollama:11434
      - PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
  ollama_data:
