version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nexus
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:postgres@localhost:5432/nexus?sslmode=disable
      - OLLAMA_URL=http://localhost:11434
      - PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    network_mode: "host"

volumes:
  postgres_data:
